env: "local"
grpc:
  port: 44044
  certs:
    ca_path: ./configs/cert/ca-auth-cert.pem
    cert_path: ./configs/cert/server-auth-cert.pem
    key_path: ./configs/cert/server-auth-key.pem
storage_cfg:
  postgres_url: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
tokens:
  token_secret: "some_random_str"
other_services:
  notification_service_url: "notifications_service:5052"
  notifications_cert:
    ca_path: ./configs/cert/ca-notifications-cert.pem
    cert_path: ./configs/cert/client-notifications-cert.pem
    key_path: ./configs/cert/client-notifications-key.pem
