env: local
storage_cfg:
  redis_url: redis://redis:6379
  password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  db: 0
grpc:
  port: 5054
  certs:
    ca_path: ./cert/ca-chat-cert.pem
    cert_path: ./cert/server-chat-cert.pem
    key_path: ./cert/server-chat-key.pem
other_services:
  auth_service_url: auth_service:5051
  auth_certs:
    ca_path: ./cert/ca-auth-cert.pem
    cert_path: ./cert/client-auth-cert.pem
    key_path: ./cert/client-auth-key.pem
  rooms_service_url: rooms_service:5053
  rooms_certs:
    ca_path: ./cert/ca-rooms-cert.pem
    cert_path: ./cert/client-rooms-cert.pem
    key_path: ./cert/client-rooms-key.pem