version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth_service:
    depends_on:
      - db
    build:
      context: ./services/auth_service
      dockerfile: Dockerfile
      args:
        config_path_from: configs/prod.yml
    ports: 
      - 5051:5051

volumes:
  postgres_data: