env: "dev"
storage_cfg:
  postgres_url: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
grpc:
  port: 5053
  private_port: 5153
  certs:
    ca_path: ./cert/ca-rooms-cert.pem
    cert_path: ./cert/server-rooms-cert.pem
    key_path: ./cert/server-rooms-key.pem
other_services:
  private_auth_service_url: "auth_service:5151"
  private_auth_cert:
    ca_path: ./cert/ca-auth-cert.pem
    cert_path: ./cert/client-auth-cert.pem
    key_path: ./cert/client-auth-key.pem