env: "local"
storage_cfg:
  postgres_url: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable" # FIXME
grpc:
  port: 44034
  certs:
    ca_path: ./configs/cert/ca-rooms-cert.pem
    cert_path: ./configs/cert/server-rooms-cert.pem
    key_path: ./configs/cert/server-rooms-key.pem
other_services:
  private_auth_service_url: localhost:44045
  private_auth_cert:
    ca_path: ./configs/cert/ca-auth-cert.pem
    cert_path: ./configs/cert/client-auth-cert.pem
    key_path: ./configs/cert/client-auth-key.pem